### ISSUE TITLE
android run time error

### ISSUE THREAD

**Issue by myebola** [medlmobileenterprises/react-native-wowza-gocoder#15]
My develop environment is:
react-native@0.44.0
react-native-wowza-gocoder@1.0.3
Wowza GoCoder SDK 1.0.1 build 346

The same code works fine for iOS.
But have run time errors for Android:
Here are my error messages:

04-07 16:14:23.608 1363-1363/com.scppublisher E/unknown:React: Exception in native call java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wowza.gocoder.sdk.api.WowzaGoCoder.setConfig(com.wowza.gocoder.sdk.api.configuration.WowzaConfig)' on a null object reference at com.rngocoder.BroadcastManager.initBroadcast(BroadcastManager.java:34) at com.rngocoder.BroadcastView.onHostResume(BroadcastView.java:89) at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:160) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5451) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Any suggestions?

**Comment by myebola** [comment]
After issue another license which tie to my android package name.
The problem is solved.
