### ISSUE TITLE
Not working on android - Attempt to invoke virtual method 'void com.wowza.gocoder.sdk.api.WowzaGoCoder.setConfig(com.wowza.gocoder.sdk.api.configuration.WowzaConfig)' on a null object reference

### ISSUE THREAD

**Issue by addingama** [medlmobileenterprises/react-native-wowza-gocoder#32]
Hi,

I'm having trouble with the android.
I've followed all the steps from readme but I got this error when running the app.
I'm using GoCoder SDK Version : 1.0.2

```
06-05 14:04:26.921 29223-29223/com.cameradispatch E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wowza.gocoder.sdk.api.WowzaGoCoder.setConfig(com.wowza.gocoder.sdk.api.configuration.WowzaConfig)' on a null object reference
        at com.rngocoder.BroadcastManager.initBroadcast(BroadcastManager.java:34)
        at com.rngocoder.BroadcastView.onHostResume(BroadcastView.java:93)
        at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:150)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

Environment
```
System
  platform           darwin
  arch               x64
  cpu                4 cores                                             Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz

JavaScript
  node               10.2.0       /usr/local/bin/node
  npm                6.1.0        /usr/local/bin/npm
  yarn               1.5.1        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.55.4

Ignite
  ignite             2.1.0        /usr/local/bin/ignite

Android
  java               1.8.0_121    /usr/bin/java
  android home       -            /Users/gama/Library/Android/sdk

iOS
  xcode              9.4
```

**Comment by pranay-medlmobile** [comment]
Possibly related to closed issue #15. Try getting a license key tied to your Android package name and see if that fixes the crash.

**Comment by countaight** [comment]
I believe this has to do with the GoCoder SDK deprecating some of its methods. I had to rewrite some of the files. How do I submit the fix for review since I've never done something like this?
